spring.application.name=Sistema-AgroTech

#ACCESO A LA BASE DE DATOS
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=Data Source=(localdb)\MSSQLLocalDB;Initial Catalog="Sistema AgroTech";Integrated Security=True;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Application Name="SQL Server Management Studio";Command Timeout=0
spring.datasource.username=Sistema AgroTech
spring.datasource.password=AGROTECH2026

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
debug=true