spring.application.name=Sistema-AgroTech

#ACCESO A LA BASE DE DATOS
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=MSSQLLocalDB;databaseName=AgroTech;encrypt=false;trustServerCertificate=true;
spring.datasource.username=AgroTech
spring.datasource.password=Admin2323

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
debug=true